export const CHANGE_THEME = 'CHANGE_THEME';

export const BOOKS_REQUESTED = 'BOOKS_REQUESTED';
export const BOOKS_FULFILLED = 'BOOKS_FULFILLED';
export const BOOKS_REJECTED = 'BOOKS_REJECTED';

export const REQUESTED_PLAN_STUDY = 'REQUESTED_PLAN_STUDY';
export const REJECTED_PLAN_STUDY = 'REJECTED_PLAN_STUDY';
export const FETCHED_PLAN_STUDY = 'FETCHED_PLAN_STUDY';

export const AUTH_FULFILLED = 'AUTH_FULFILLED';
export const AUTH_REJECTED = 'AUTH_REJECTED';
export const AUTH_REQUESTED = 'AUTH_REQUESTED';

export const REQUESTED_HACKER_NEWS = 'REQUESTED_HACKER_NEWS';
export const FETCHED_HACKER_NEWS = 'FETCHED_HACKER_NEWS';
export const REJECTED_HACKER_NEWS = 'REJECTED_HACKER_NEWS';
